#pragma once

#define TRACKED_SPACE_LIST(X) \
    X(Player) \
    X(LeftController) \
    X(RightController) \
    X(Head) \
    X(LeftHand) \
    X(RightHand) \
    X(LeftHandJoint0) \
    X(LeftHandJoint1) \
    X(LeftHandJoint2) \
    X(LeftHandJoint3) \
    X(LeftHandJoint4) \
    X(LeftThumbTip) \
    X(LeftHandJoint6) \
    X(LeftHandJoint7) \
    X(LeftHandJoint8) \
    X(LeftHandJoint9) \
    X(LeftIndexTip) \
    X(LeftHandJoint11) \
    X(LeftHandJoint12) \
    X(LeftHandJoint13) \
    X(LeftHandJoint14) \
    X(LeftMiddleTip) \
    X(LeftHandJoint16) \
    X(LeftHandJoint17) \
    X(LeftHandJoint18) \
    X(LeftHandJoint19) \
    X(LeftRingTip) \
    X(LeftHandJoint21) \
    X(LeftHandJoint22) \
    X(LeftHandJoint23) \
    X(LeftHandJoint24) \
    X(LeftPinkyTip) \
    X(RightHandJoint0) \
    X(RightHandJoint1) \
    X(RightHandJoint2) \
    X(RightHandJoint3) \
    X(RightHandJoint4) \
    X(RightThumbTip) \
    X(RightHandJoint6) \
    X(RightHandJoint7) \
    X(RightHandJoint8) \
    X(RightHandJoint9) \
    X(RightIndexTip) \
    X(RightHandJoint11) \
    X(RightHandJoint12) \
    X(RightHandJoint13) \
    X(RightHandJoint14) \
    X(RightMiddleTip) \
    X(RightHandJoint16) \
    X(RightHandJoint17) \
    X(RightHandJoint18) \
    X(RightHandJoint19) \
    X(RightRingTip) \
    X(RightHandJoint21) \
    X(RightHandJoint22) \
    X(RightHandJoint23) \
    X(RightHandJoint24) \
    X(RightPinkyTip) \
